services:
  - type: web
    name: noor-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: TURSO_DATABASE_URL
        sync: false
      - key: TURSO_AUTH_TOKEN
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: TELEGRAM_REPORT_BOT
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
